# Generated by Django 5.2.6 on 2026-02-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('nombre_mascota', models.CharField(max_length=100, verbose_name='Nombre Mascota')),
                ('tipo_consulta', models.CharField(choices=[('Emergencia', 'Emergencia'), ('Solicitar Turno', 'Solicitar Turno'), ('Consulta General', 'Consulta General'), ('Atención a Domicilio', 'Atención a Domicilio'), ('Peluquería', 'Peluquería'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='Tipo de Consulta')),
                ('mensaje', models.TextField(max_length=500, verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
        ),
    ]
