# Generated by Django 5.2.6 on 2026-05-13 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='user',
            new_name='tutor',
        ),
    ]
