# Generated by Django 5.2.6 on 2026-06-15 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_rename_user_tutor_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
