# Generated by Django 5.2.6 on 2026-03-10 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='Slug')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('bajada', models.CharField(max_length=400, verbose_name='Bajada')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/img/', verbose_name='Imagen')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='Slug')),
                ('publicado', models.BooleanField(default=False, verbose_name='¿Publicado?')),
                ('tiempo', models.CharField(default=5, max_length=3, verbose_name='Tiempo de Lectura')),
                ('publicado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categorias', models.ManyToManyField(blank=True, to='blog.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-publicado_en'],
            },
        ),
    ]
