# Generated by Django 5.2.6 on 2026-03-11 15:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contenido',
        ),
        migrations.AddField(
            model_name='post',
            name='contenido1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='contenido2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='frase',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Frase Destacada'),
        ),
    ]
