# Generated by Django 5.2.6 on 2026-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_contenido_post_contenido1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorias',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=True, verbose_name='¿Publicado?'),
        ),
    ]
