# Generated by Django 5.2.6 on 2026-02-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, null=True, verbose_name='Apellido')),
                ('nombre_mascota', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('tipo_mascota', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=10, null=True, verbose_name='Tipo de Mascota')),
                ('email', models.EmailField(max_length=40, null=True, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, null=True, verbose_name='Dirección')),
                ('fecha_preferida', models.DateField(null=True, verbose_name='Fecha Preferida')),
                ('horario_preferido', models.CharField(choices=[('Mañana (9:00 a 12:00)', 'Mañana (9:00 a 12:00)'), ('Tarde (14:00 a 16:00)', 'Tarde (14:00 a 16:00)'), ('Noche (16:00 a 20:00)', 'Noche (16:00 a 20:00)'), ('Sábado (9:00 a 12:00)', 'Sábado (9:00 a 12:00)')], max_length=30, null=True, verbose_name='Horario Preferido')),
                ('urgencia', models.CharField(choices=[('Normal (24 a 48 hs)', 'Normal (24 a 48 hs)'), ('Urgente (Mismo día)', 'Urgente (Mismo día)'), ('Emergencia (Inmediato)', 'Emergencia (Inmediato)')], max_length=30, null=True, verbose_name='Urgencia')),
                ('notas_adicionales', models.TextField(blank=True, max_length=250, verbose_name='Notas Adicionales')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
        ),
    ]
