# Generated by Django 5.2.6 on 2026-03-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domicilio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['nombre'], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
