# Generated by Django 5.2.6 on 2026-02-20 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0001_initial'),
        ('veterinario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10)),
                ('raza', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('color', models.CharField(help_text='Color o particularidad para identificar', max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='tutor.tutor')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('cirugia', 'Cirugía'), ('emergencia', 'Emergencia'), ('control', 'Control'), ('otro', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
                ('motivo_consulta', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('examenes', models.TextField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proxima_visita', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinario.veterinario')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='mascota.mascota')),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('radiografia', 'Radiografía'), ('analisis', 'Análisis'), ('ecografia', 'Ecografía'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='archivos_mascotas/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='mascota.historialmedico')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='mascota.mascota')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='mascota.mascota')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinario.veterinario')),
            ],
            options={
                'verbose_name': 'Registro de Vacunación',
                'verbose_name_plural': 'Registros de Vacunación',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
