# Generated by Django 5.2.6 on 2026-04-27 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
        ('veterinario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAntiparasitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('antiparasitario', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('peso_en_fecha', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg al momento del control', max_digits=5, null=True)),
                ('proxima_desparasitacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antiparasitarios', to='mascota.mascota')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinario.veterinario')),
            ],
            options={
                'verbose_name': 'Control Antiparasitario',
                'verbose_name_plural': 'Controles Antiparasitarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
