# Generated by Django 5.2.6 on 2026-04-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_controlantiparasitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura en cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('saludable', 'Saludable'), ('chequeo', 'Chequeo'), ('critico', 'Crítico')], default='saludable', max_length=20),
        ),
    ]
