# Generated by Django 5.2.6 on 2026-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_mascota_altura_mascota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.CharField(help_text='Color o particularidad para identificar', max_length=100, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='microchip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Microchip'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=100, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10, verbose_name='Tipo'),
        ),
    ]
